# Turns src/shaders/*.{vert,frag,comp} into a single header of string literals.
# Keeping shaders in the binary means the service either starts correctly or
# fails at link time -- there is no "installed but missing a shader" state.
file(GLOB SHADERS ${SHADER_DIR}/*.vert ${SHADER_DIR}/*.frag ${SHADER_DIR}/*.comp)
list(SORT SHADERS)

set(OUT "// Generated by cmake/EmbedShaders.cmake -- do not edit.\n")
string(APPEND OUT "#pragma once\n#include <string_view>\n\nnamespace nova::shaders {\n\n")

foreach(SHADER ${SHADERS})
  get_filename_component(NAME ${SHADER} NAME)
  string(REPLACE "." "_" SYMBOL ${NAME})
  file(READ ${SHADER} CONTENT)
  string(APPEND OUT "inline constexpr std::string_view ${SYMBOL} = R\"GLSL(\n${CONTENT}\n)GLSL\";\n\n")
endforeach()

string(APPEND OUT "}  // namespace nova::shaders\n")

get_filename_component(OUT_DIR ${OUTPUT} DIRECTORY)
file(MAKE_DIRECTORY ${OUT_DIR})
file(WRITE ${OUTPUT} "${OUT}")
